spring:
   thymeleaf:
       cache: false
       prefix: classpath:/templates/
       suffix: .html
       encoding: UTF-8
       mode: HTML5
   datasource:
       driver-class-name: com.mysql.cj.jdbc.Driver
       url: jdbc:mysql://localhost:3306/news01?useUnicode=true&characterEncoding=utf-8
#       url: jdbc:mysql://mysql:3306/news01?useUnicode=true&characterEncoding=utf-8

       username: root
       password: aceracer123

   flyway:
       enabled: true               # 啟用 Flyway Migration
       locations: classpath:db/migration # Migration 檔案存放的資料夾
       # 以下是資料庫的連線設定
#       url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
       url: ${spring.datasource.url}
       user: root
       password: aceracer123
       baseline-on-migrate: true
       # 由於是用 postgres 所以需要設定 schema，並且如果不存在會自動建立



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl